## Creating Numpy Arrays

From a Python List

In [2]:
my_list = [1,2,3]

import numpy as np
np.array(my_list)

array([1, 2, 3])

In [3]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Built in Methods

In [7]:
#arange
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [9]:
#zeroes and ones
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
#linspace - evenly spaced numbers between a range

np.linspace(0, 20, 5)



array([ 0.,  5., 10., 15., 20.])

In [21]:
#eye - identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Random

In [22]:
#rand - between 0 to 1 - uniform distribution
np.random.rand(4)

array([0.8364814 , 0.23185358, 0.66666542, 0.23814623])

In [23]:
np.random.rand(5,5)

array([[0.1208021 , 0.79431517, 0.60764684, 0.63694197, 0.0782117 ],
       [0.79121548, 0.72232705, 0.63012747, 0.06494879, 0.40600389],
       [0.13463304, 0.05350676, 0.61300151, 0.46028614, 0.49553505],
       [0.80417529, 0.57669318, 0.83829777, 0.84692706, 0.52775048],
       [0.36977033, 0.63565049, 0.07362856, 0.16214845, 0.80116745]])

In [24]:
#randn - standard normal distribution

np.random.randn(3)

array([-0.56423432, -1.94083283, -0.65574714])

In [26]:
np.random.randn(4,4)

array([[ 0.11655903,  1.35323689,  0.77316143, -0.37121908],
       [-0.62216928,  0.04656213, -2.63168409,  0.37519555],
       [-1.54662077,  1.19657963,  0.9891485 , -1.3202171 ],
       [-0.38289493, -0.59245399, -0.84539574, -0.95490739]])

In [27]:
#randint - low and high, low is inclusive and high is exclusive

np.random.randint(1,100,2)

array([49, 52])

In [30]:
np.random.randint(1, 50, 4)

array([48, 40, 25, 47])

#### Array Attributes and Methods

In [35]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [36]:
ranarr = np.random.randint(0,50,10)
ranarr

array([ 4, 49, 27, 16, 10, 34, 12, 12, 10, 30])

In [38]:
#Reshape
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [40]:
#max
ranarr.max()

49

In [41]:
#min
ranarr.min()

4

In [42]:
#argmax - index pof largest number
ranarr.argmax()

1

In [43]:
#argmin - index of smallest number
ranarr.argmin()

0

In [45]:
#Shape
arr.shape

(25,)

In [46]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
arr.shape

(25,)

In [50]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [51]:
#dtype
arr.dtype

dtype('int64')