### Numpy Indexing and Selection

In [1]:
import numpy as np
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [2]:
#print element at index 8
arr[8]

8

In [4]:
#print range of numbers in an array or list using slice notations
arr[1:5]

array([1, 2, 3, 4])

In [5]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [6]:
#print everything upto index 8, the element at index 8 is not printed
arr[:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [7]:
#print everything beyond index 5, so element at index 5 is not included
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

#### Broadcasting using arrays

In [8]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

Data is not copied to new arrays, justification below

In [10]:
slice_of_arr = arr[0:6]
slice_of_arr

array([100, 100, 100, 100, 100,   5])

In [11]:
slice_of_arr[0:5] = 99
slice_of_arr 

array([99, 99, 99, 99, 99,  5])

In [12]:
#looking at the original array, we can observe that the original array has been updated
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

To create a copy of the array, use the copy() method

In [14]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [15]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [16]:
#Looking at the original array, we can see it is unaffected
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

### Creating, indexing and selecting 2D arrays

In [19]:
arr_2d = np.array([[5,10,15],[2,9,18], [23,4,60]])
arr_2d

array([[ 5, 10, 15],
       [ 2,  9, 18],
       [23,  4, 60]])

In [20]:
#double bracket indexing method
arr_2d[0][0]

5

In [21]:
#use single bracket to get entire row
arr_2d[0]

array([ 5, 10, 15])

In [22]:
#single bracket indexing method
arr_2d[0,1]

10

In [23]:
#Exercise - print 60 in the array
arr_2d[2,2]

60

Grab slice of 2d array

In [26]:
#grab upper right corner
arr_2d[:2, 1:] #first row is specified then column

array([[10, 15],
       [ 9, 18]])

In [27]:
#Exercise - grab bottom two rows
arr_2d[1:, :]

array([[ 2,  9, 18],
       [23,  4, 60]])

In [28]:
#Exercise - grab upper right corner
arr_2d[:2, :2]

array([[ 5, 10],
       [ 2,  9]])

Conditional selection

In [30]:
#creating a new array
array = np.arange(1,11)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
#get array of boolean values
bool_arr = array > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [35]:
#get the values where bool_arr is True. This is an example of conditionally selecting array
array[bool_arr]

array([ 6,  7,  8,  9, 10])

In [36]:
#print array elements less than 5
array[array < 5]

array([1, 2, 3, 4])

In [38]:
#creating 2d array with arange
array_2d = np.arange(0,50).reshape(5,10)
array_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [45]:
#Exercise - Grab 13, 14, 23, 24 from above array
array_2d[1:3, 3:5]

array([[13, 14],
       [23, 24]])